name: new project
on: push
jobs:
  project:
    runs-on: ubuntu-latest 
    steps:
      - name: Get new code
        uses: actions/checkout@v3
      - name: set NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: install dependencies
        run: npm ci
      - name: run tests
        run: npm test
      - name: run lint
        run: npm lint   

  deployment:
    needs: project 
    runs-on: ubuntu-latest 
    steps:
      - name: Get new code
        uses: actions/checkout@v3
      - name: set NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: install dependencies
        run: npm ci
      - name: build project
        run: echo "deploying ... "